[project]
name = "aesop-embed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "chromadb>=1.0.12",
    "numpy>=2.2.6",
    "requests>=2.32.3",
    "sentence-transformers>=4.1.0",
]
